apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.collab.name }}
  labels:
    {{- include "blossom.collabLabels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    {{- include "blossom.collabSelector" . | nindent 4 }}
  ports:
    - port: {{ .Values.collab.containerPort }}
      targetPort: {{ .Values.collab.containerPort }}
      nodePort: {{ .Values.collab.nodePort }}
      name: ws
