apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-config
  labels:
    {{- include "blossom.labels" . | nindent 4 }}
data:
  COLLAB_PORT: {{ .Values.config.collabPort | quote }}
  NEXT_PUBLIC_WS_URL: {{ .Values.config.nextPublicWsUrl | quote }}
  AUTH_URL: {{ .Values.config.authUrl | quote }}
