apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secrets
  labels:
    {{- include "blossom.labels" . | nindent 4 }}
type: Opaque
stringData:
  AUTH_SECRET: {{ .Values.secret.authSecret | quote }}
  DATABASE_URL: {{ .Values.secret.databaseUrl | quote }}
