apiVersion: v1
kind: Service
metadata:
  name: google-docs-app
  labels:
    app: google-docs
    component: app
spec:
  type: NodePort
  selector:
    app: google-docs
    component: app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31336
      name: http
