apiVersion: v1
kind: Service
metadata:
  name: google-docs-collab
  labels:
    app: google-docs
    component: collab
spec:
  type: NodePort
  selector:
    app: google-docs
    component: collab
  ports:
    - port: 1234
      targetPort: 1234
      nodePort: 32653
      name: ws
