apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - secret.yaml
  - app-deployment.yaml
  - app-service.yaml
  - collab-deployment.yaml
  - collab-service.yaml
