apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: cpu-stress-app
  labels:
    app: google-docs
    component: chaos
spec:
  mode: all
  selector:
    labelSelectors:
      app: google-docs
      component: app
  stressors:
    cpu:
      workers: 2
      load: 80
  duration: "5m"
